const listings=[
{id:'YM-1042',title:'CAT 320 Excavator',cat:'Excavator',type:'hire',loc:'Ikeja, Lagos',price:'₦85,000',unit:'/ day',rating:'4.8 ★ (32)',image:'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=900&q=80',description:'A dependable 20-ton excavator with an experienced operator available on request.'},
{id:'YM-1043',title:'Liebherr LTM Mobile Crane',cat:'Crane',type:'lease',loc:'Apapa, Lagos',price:'₦1.2M',unit:'/ month',rating:'4.9 ★ (18)',image:'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=900&q=80',description:'Mobile crane with a 40m reach, maintained and ready for long-term site work.'},
{id:'YM-1044',title:'Bobcat S650 Skid Steer',cat:'Loader',type:'hire',loc:'Lekki, Lagos',price:'₦42,000',unit:'/ day',rating:'4.6 ★ (54)',image:'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bc/Hydraulic_breaker_attachment_on_a_skid-steer_loader.webm/960px--Hydraulic_breaker_attachment_on_a_skid-steer_loader.webm.jpg',description:'Compact loader for tight sites, landscaping, cleanup, and material movement.'},
{id:'YM-1045',title:'Perkins 100kVA Generator',cat:'Generator',type:'sale',loc:'Ajah, Lagos',price:'₦6.5M',unit:'fixed',rating:'4.7 ★ (11)',image:'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=900&q=80',description:'Low-hour diesel generator with service history and delivery available.'},
{id:'YM-1046',title:'Komatsu D65 Bulldozer',cat:'Bulldozer',type:'hire',loc:'Ibadan',price:'₦95,000',unit:'/ day',rating:'4.5 ★ (9)',image:'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&fit=crop&w=900&q=80',description:'Heavy-duty dozer suited to clearing, grading, and earthmoving jobs.'},
{id:'YM-1047',title:'Concrete Mixer Truck 6m³',cat:'Concrete mixer',type:'lease',loc:'Ikorodu, Lagos',price:'₦380,000',unit:'/ month',rating:'4.4 ★ (22)',image:'https://images.unsplash.com/photo-1590479773265-7464e5d48118?auto=format&fit=crop&w=900&q=80',description:'Reliable mixer truck with scheduled maintenance and flexible lease terms.'},
{id:'YM-1048',title:'Scaffolding Set, 200m²',cat:'Scaffolding',type:'sale',loc:'Yaba, Lagos',price:'₦2.1M',unit:'fixed',rating:'4.9 ★ (40)',image:'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=900&q=80',description:'Complete inspected scaffolding package for commercial and residential work.'},
{id:'YM-1049',title:'JCB 3CX Backhoe Loader',cat:'Loader',type:'hire',loc:'Surulere, Lagos',price:'₦58,000',unit:'/ day',rating:'4.7 ★ (27)',image:'https://images.unsplash.com/photo-1574359411659-15573a27fd0c?auto=format&fit=crop&w=900&q=80',description:'Versatile backhoe loader with quick booking availability across Lagos.'},
{id:'YM-1050',title:'Tower Crane, 45m Reach',cat:'Crane',type:'sale',loc:'Victoria Island, Lagos',price:'₦48M',unit:'fixed',rating:'5.0 ★ (4)',image:'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=900&q=80',description:'Tower crane package for high-rise projects, including dismantling support.'}
];
const mechanics=[{name:'Chidi Okafor',spec:'Hydraulics & excavator repair',loc:'Ikeja, Lagos',badges:['12 yrs exp','Mobile callout'],rating:'4.9 ★ (61 jobs)'},{name:'Ekanem Okon',spec:'Diesel engines & generators',loc:'Ajah, Lagos',badges:['Certified CAT tech'],rating:'4.8 ★ (37 jobs)'},{name:'Tunde Ajibulu',spec:'Crane inspection & certification',loc:'Apapa, Lagos',badges:['Licensed inspector'],rating:'5.0 ★ (15 jobs)'}];
const page=document.body.dataset.page;
function header(){const active=page==='home'?'':page;document.getElementById('site-header').innerHTML=`<header><div class="wrap header-row"><a class="logo" href="index.html"><span class="logo-mark" aria-hidden="true"></span>YardMeet</a><nav aria-label="Primary"><a href="browse.html" ${active==='browse'?'aria-current="page"':''}>Browse</a><a href="services.html" ${active==='services'?'aria-current="page"':''}>Mechanics & service</a><a href="how-it-works.html" ${active==='how'?'aria-current="page"':''}>How it works</a><a href="post.html" ${active==='post'?'aria-current="page"':''}>Post a listing</a></nav><div class="header-actions"><a class="btn primary header-post" href="post.html">List equipment</a><button class="menu-toggle" aria-expanded="false" aria-label="Open menu">Menu</button></div></div></header>`;const row=document.querySelector('.header-row');document.querySelector('.menu-toggle').addEventListener('click',e=>{const open=row.classList.toggle('menu-open');e.currentTarget.setAttribute('aria-expanded',open)});}
function footer(){document.getElementById('site-footer').innerHTML=`<footer><div class="wrap"><div class="footer-grid"><div class="footer-col"><h4>YardMeet</h4><a href="browse.html">Browse equipment</a><a href="services.html">Find a mechanic</a><a href="post.html">Post a listing</a></div><div class="footer-col"><h4>For owners</h4><a href="post.html">List a machine</a><a href="how-it-works.html">How it works</a><a href="post.html">Get verified</a></div><div class="footer-col"><h4>For mechanics</h4><a href="services.html">Create a profile</a><a href="post.html?type=service">Request a job</a><a href="services.html">Pricing guide</a></div><div class="footer-col"><h4>Support</h4><a href="how-it-works.html">Help center</a><a href="mailto:hello@yardmeet.example">Contact</a></div></div><div class="foot-bottom"><span>© 2026 YardMeet — a demo marketplace model.</span><span>Lagos, Nigeria</span></div></div></footer>`;}
function tagLabel(type){return {hire:'For hire',lease:'For lease',sale:'For sale'}[type]}
const defaultReviews={machine:{'YM-1042':[{name:'Ayo Contractor',rating:5,text:'Strong machine and the owner delivered on time.'}]},owner:{'owner-1042':[{name:'Musa Hirer',rating:5,text:'Clear communication and honest equipment details.'}]},contractor:{'contractor-lagos':[{name:'Ifeoma Site Lead',rating:4,text:'Professional crew and smooth handover.'}]},mechanic:{'Chidi Okafor':[{name:'Kunle Hirer',rating:5,text:'Chidi diagnosed the hydraulic issue quickly.'}]}};
function getReviews(type,id){const stored=JSON.parse(localStorage.getItem('yardmeet-reviews')||'{}');return [...(defaultReviews[type]?.[id]||[]),...(stored[type]?.[id]||[])];}
function saveReview(type,id,review){const stored=JSON.parse(localStorage.getItem('yardmeet-reviews')||'{}');stored[type]??={};stored[type][id]??=[];stored[type][id].push(review);localStorage.setItem('yardmeet-reviews',JSON.stringify(stored));}
function escapeHTML(value){return String(value).replace(/[&<>'"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));}
function reviewMarkup(type,id,label){const reviews=getReviews(type,id);return `<section class="reviews" data-review-type="${type}" data-review-id="${escapeHTML(id)}"><div class="review-heading"><h3>${label} reviews</h3><span>${reviews.length} review${reviews.length===1?'':'s'}</span></div><div class="review-list">${reviews.length?reviews.map(review=>`<article class="review"><div><strong>${escapeHTML(review.name)}</strong><span class="review-stars">${'★'.repeat(Number(review.rating))}${'☆'.repeat(5-Number(review.rating))}</span></div><p>${escapeHTML(review.text)}</p></article>`).join(''):'<p class="review-empty">No reviews yet. Be the first hirer to share feedback.</p>'}</div><form class="review-form"><label>Your name<input name="name" required placeholder="e.g. Tobi Contractor"></label><label>Rating<select name="rating" required><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select></label><label class="review-wide">Comment<textarea name="text" required placeholder="How was the machine, owner, contractor, or mechanic?"></textarea></label><button class="btn primary" type="submit">Post review</button></form></section>`;}
function wireReviewForms(root){root.querySelectorAll('.review-form').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();const section=form.closest('.reviews');const data=new FormData(form);saveReview(section.dataset.reviewType,section.dataset.reviewId,{name:data.get('name'),rating:data.get('rating'),text:data.get('text')});section.outerHTML=reviewMarkup(section.dataset.reviewType,section.dataset.reviewId,section.querySelector('.review-heading h3').textContent.replace(' reviews',''));wireReviewForms(root);}));}
function openListing(listing){const backdrop=document.createElement('div');backdrop.className='modal-backdrop';backdrop.innerHTML=`<div class="modal modal-wide" role="dialog" aria-modal="true" aria-label="${escapeHTML(listing.title)}"><button class="modal-close" aria-label="Close details">×</button><span class="tag ${listing.type}">${tagLabel(listing.type)}</span><h2>${escapeHTML(listing.title)}</h2><p>${escapeHTML(listing.description)}</p><p><strong>${escapeHTML(listing.cat)}</strong> · ${escapeHTML(listing.loc)}<br><strong>${escapeHTML(listing.price)}</strong> ${escapeHTML(listing.unit)} · ${escapeHTML(listing.rating)}</p><a class="btn primary" href="mailto:hello@yardmeet.example?subject=Enquiry about ${encodeURIComponent(listing.title)}">Contact owner</a><div class="profile-review-grid"><div>${reviewMarkup('machine',listing.id,'Machine')}</div><div>${reviewMarkup('owner','owner-'+listing.id.slice(-4),'Owner profile')}</div><div>${reviewMarkup('contractor','contractor-lagos','Contractor profile')}</div></div></div>`;document.body.appendChild(backdrop);wireReviewForms(backdrop);const close=()=>backdrop.remove();backdrop.addEventListener('click',e=>{if(e.target===backdrop)close()});backdrop.querySelector('.modal-close').addEventListener('click',close);}
function renderListings(filter,query){const grid=document.getElementById('listingsGrid');if(!grid)return;const q=(query||'').toLowerCase().trim();const filtered=listings.filter(l=>(filter==='all'||l.type===filter)&&(!q||[l.title,l.cat,l.loc].join(' ').toLowerCase().includes(q)));grid.innerHTML='';filtered.forEach(l=>{const card=document.createElement('article');card.className='card';card.tabIndex=0;card.innerHTML=`<div class="card-media" style="background-image:url('${l.image}')"><span class="tag ${l.type}">${tagLabel(l.type)}</span><span class="asset-id">${l.id}</span></div><div class="card-body"><h3>${l.title}</h3><div class="card-meta"><span>${l.cat}</span><span>${l.loc}</span></div><div class="card-price"><div><span class="price-num">${l.price}</span> <span class="price-unit">${l.unit}</span></div><div class="rating">${l.rating}</div></div></div>`;card.addEventListener('click',()=>openListing(l));card.addEventListener('keydown',e=>{if(e.key==='Enter')openListing(l)});grid.appendChild(card)});document.getElementById('emptyState').hidden=filtered.length>0;document.getElementById('resultCount').textContent=`${filtered.length} result${filtered.length===1?'':'s'}`;}
function initBrowse(){let active=new URLSearchParams(location.search).get('filter')||'all';const input=document.getElementById('searchInput');document.querySelectorAll('.chip').forEach(chip=>chip.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(c=>c.classList.remove('active'));chip.classList.add('active');active=chip.dataset.filter;document.getElementById('listingsTitle').textContent={all:'All listings',hire:'Available for hire',lease:'Available for lease',sale:'For sale'}[active];renderListings(active,input.value)}));input.addEventListener('input',()=>renderListings(active,input.value));document.querySelectorAll('.chip').forEach(c=>c.classList.toggle('active',c.dataset.filter===active));renderListings(active,'');}
function initServices(){const grid=document.getElementById('mechGrid');if(!grid)return;mechanics.forEach(m=>{const card=document.createElement('article');card.className='mech-card';card.innerHTML=`<div class="mech-avatar">${m.name.split(' ').map(w=>w[0]).join('')}</div><div class="mech-info"><h3>${escapeHTML(m.name)}</h3><div class="spec-list">${escapeHTML(m.spec)} · ${escapeHTML(m.loc)}</div><div>${m.badges.map(b=>`<span class="badge">${escapeHTML(b)}</span>`).join('')}</div><div class="rating" style="margin-top:9px">${escapeHTML(m.rating)}</div><a class="text-link" style="display:inline-block;margin-top:13px" href="post.html?type=service&mechanic=${encodeURIComponent(m.name)}">Request this tech →</a><button class="profile-review-button" type="button">Review mechanic profile</button><div class="mechanic-review-panel" hidden>${reviewMarkup('mechanic',m.name,'Mechanic profile')}</div></div>`;grid.appendChild(card);card.querySelector('.profile-review-button').addEventListener('click',()=>{const panel=card.querySelector('.mechanic-review-panel');panel.hidden=!panel.hidden;if(!panel.hidden)wireReviewForms(panel);});});}
function initPost(){const params=new URLSearchParams(location.search);const chosen=params.get('type');if(chosen){document.querySelectorAll('.type-opt').forEach(opt=>opt.classList.toggle('active',opt.dataset.type===chosen));}document.querySelectorAll('.type-opt').forEach(opt=>opt.addEventListener('click',()=>{document.querySelectorAll('.type-opt').forEach(o=>o.classList.remove('active'));opt.classList.add('active')}));document.getElementById('postForm').addEventListener('submit',e=>{e.preventDefault();document.getElementById('formSuccess').hidden=false;e.target.querySelector('button[type=submit]').textContent='Published (demo)';});}
function initWelcome(){const screen=document.getElementById('welcomeScreen');const enter=document.getElementById('enterSite');if(!screen||!enter)return;enter.addEventListener('click',()=>{screen.classList.add('is-hidden');setTimeout(()=>screen.remove(),500);});}
header();footer();if(page==='home'){initWelcome();initBrowse();initServices();initPost();document.querySelector('nav a[href="browse.html"]').href='#browse';document.querySelector('nav a[href="services.html"]').href='#services';document.querySelector('nav a[href="how-it-works.html"]').href='#how';document.querySelectorAll('nav a[href="post.html"]').forEach(link=>link.href='#post');}if(page==='browse')initBrowse();if(page==='services')initServices();if(page==='post')initPost();